const { create } = require('xmlbuilder2');

/**
 * Função para gerar o XML da NF-e
 * @param {Object} nfeData - Dados da venda e do cliente
 * @returns {string} - XML da NF-e em formato string
 */
function gerarXmlNfe(nfeData) {
    const { venda, cliente } = nfeData;

    // Criar documento XML
    const doc = create({ version: '1.0', encoding: 'UTF-8' })
        .ele('NFe')
            .ele('infNFe', { Id: `NFe${venda.id_venda_ml}`, versao: '4.00' })
                .ele('ide')
                    .ele('cUF').txt('35').up() // código do estado (SP = 35)
                    .ele('natOp').txt('Venda de mercadorias').up()
                    .ele('mod').txt('55').up()
                    .ele('serie').txt('1').up()
                    .ele('nNF').txt('1').up()
                    .ele('dhEmi').txt(new Date().toISOString()).up()
                    .ele('tpNF').txt('1').up() // saída
                    .ele('idDest').txt('1').up()
                    .ele('cMunFG').txt('3550308').up() // código município SP
                    .ele('tpImp').txt('1').up()
                    .ele('tpEmis').txt('1').up()
                    .ele('cDV').txt('0').up()
                    .ele('tpAmb').txt('2').up() // 2 = homologação
                    .ele('finNFe').txt('1').up()
                    .ele('indFinal').txt('1').up()
                    .ele('indPres').txt('1').up()
                    .ele('procEmi').txt('0').up()
                    .ele('verProc').txt('1.0').up()
                .up()
                .ele('emit')
                    .ele('CNPJ').txt('00000000000000').up()
                    .ele('xNome').txt('Minha Empresa LTDA').up()
                    .ele('enderEmit')
                        .ele('xLgr').txt('Rua Exemplo').up()
                        .ele('nro').txt('123').up()
                        .ele('xBairro').txt('Centro').up()
                        .ele('cMun').txt('3550308').up()
                        .ele('xMun').txt('São Paulo').up()
                        .ele('UF').txt('SP').up()
                        .ele('CEP').txt('01000000').up()
                        .ele('cPais').txt('1058').up()
                        .ele('xPais').txt('Brasil').up()
                    .up()
                    .ele('IE').txt('123456789').up()
                    .ele('CRT').txt('1').up()
                .up()
                .ele('dest')
                    .ele(cliente.identification.type === 'CNPJ' ? 'CNPJ' : 'CPF')
                        .txt(cliente.identification.number).up()
                    .ele('xNome').txt(cliente.name).up()
                    .ele('enderDest')
                        .ele('xLgr').txt(cliente.address.street_name).up()
                        .ele('nro').txt(cliente.address.street_number || 'SN').up()
                        .ele('xBairro').txt(cliente.address.neighborhood || '').up()
                        .ele('cMun').txt('3550308').up()
                        .ele('xMun').txt(cliente.address.city_name).up()
                        .ele('UF').txt(cliente.address.state.name).up()
                        .ele('CEP').txt(cliente.address.zip_code).up()
                        .ele('cPais').txt('1058').up()
                        .ele('xPais').txt('Brasil').up()
                    .up()
                    .ele('indIEDest').txt('9').up()
                .up()
                .ele('det', { nItem: '1' })
                    .ele('prod')
                        .ele('cProd').txt(venda.id_venda_ml).up()
                        .ele('xProd').txt('Produto vendido').up()
                        .ele('qCom').txt('1').up()
                        .ele('vUnCom').txt(venda.valor_total).up()
                        .ele('vProd').txt(venda.valor_total).up()
                        .ele('CFOP').txt('5102').up()
                        .ele('uCom').txt('UN').up()
                    .up()
                    .ele('imposto')
                        .ele('ICMS')
                            .ele('ICMSSN102')
                                .ele('orig').txt('0').up()
                                .ele('CSOSN').txt('102').up()
                            .up()
                        .up()
                        .ele('PIS')
                            .ele('PISNT')
                                .ele('CST').txt('07').up()
                            .up()
                        .up()
                        .ele('COFINS')
                            .ele('COFINSNT')
                                .ele('CST').txt('07').up()
                            .up()
                        .up()
                    .up()
                .up()
                .ele('total')
                    .ele('ICMSTot')
                        .ele('vProd').txt(venda.valor_total).up()
                        .ele('vNF').txt(venda.valor_total).up()
                    .up()
                .up()
            .up()
        .up();

    return doc.end({ prettyPrint: true });
}

module.exports = { gerarXmlNfe };
